### PR TITLE
add a few functions for getting vectors out of Row fields

### PR DESCRIPTION
**Pull request by alpmestan**

### CODE REVIEW

**Comment by alpmestan** [comment]
Required for my work on interpreting `FeatureFilter` queries in leapyear-server.

**Comment by facundominguez** [comment]
Why not provide a binding to
```Haskell
getList :: Int32 -> Row -> IO [JObject]
-- or getList :: Int32 -> Row -> IO (Vector JObject)
getList i r = do
  jarraylist :: J ('Class "java.util.List") <- call r "getList" [coerce i]
  call jarraylist "toArray" [] >>= reify
```
?

Then the other calls could be written as `getList i e >>= mapM_ reify`.

**Comment by alpmestan** [comment]
@facundominguez Some instances can provide a faster path, I think.

**Comment by facundominguez** [comment]
Perhaps. These are not storable vectors though, and getList yields an array of object references, not primitive types, which is what storable vectors could optimize.

**Comment by alpmestan** [comment]
@facundominguez Right. I implemented your suggestion, PTAL.

**Pull request merged**
