### PR TITLE
Update inline-java to include ForeignPtr implementation of java refer…

### PR DESCRIPTION
**Pull request by facundominguez**
…ences.

Needs https://github.com/LeapYear/inline-java/pull/10
Required for https://github.com/LeapYear/leapyear-server/issues/949

### CODE REVIEW

**Comment by robinbb** [comment]
Blocked on error described in LeapYear/leapyear-server#949.

**Comment by robinbb** [comment]
Blocked in issue described in LeapYear/leapyear-server#949.

**Comment by facundominguez** [comment]
Was a CI specific problem unrelated to the PR.

**Comment by robinbb** [comment]
@facundominguez You will have to move this PR to the LeapYear/leapyear-sparkle repo, when the time comes.

**Pull request closed without merging**
