### PR TITLE
Bind mapPartitionsWithIndex.

### PR DESCRIPTION
**Pull request by facundominguez**
Requires https://github.com/LeapYear/inline-java/pull/5.

It defines an `aggregate'` function implemented in terms of `mapPartitions`. I left the old implementation of `aggregate` because it poses a different set of constraints. Could remove the old one if there is agreement to do so.

### CODE REVIEW

**Comment by robinbb** [comment]
When I build this, I get:

```
    Starting a Gradle Daemon (subsequent builds will be faster)
    :compileJava/Users/leapyear-robinbateboerop/LeapYear/sparkle/src/main/java/io/tweag/sparkle/HaskellIterator.java:12: error: HaskellIterator is not abstract and does not override abstract method remove() in Iterator
    public class HaskellIterator<T> extends SparkleBase
           ^
    Note: /Users/leapyear-robinbateboerop/LeapYear/sparkle/src/main/java/io/tweag/sparkle/SparkleBase.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 error
     FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 7.609 secs
    Command gradle build exited with failure code 1
    CallStack (from HasCallStack):
    error, called at
    /Users/leapyear-robinbateboerop/LeapYear/sparkle/Setup.hs:15:9 in main:Main
```

**Comment by facundominguez** [comment]
@robinbb does not fail for me like that, but see if this fixes it: https://github.com/LeapYear/sparkle/pull/20

**Comment by robinbb** [comment]
Yes, that fixed it. Sadly, this will also require an "upstream" fix, in leapyear-algorithms, to force the dependence on the correct version of this repo.

**Comment by robinbb** [comment]
I made that "upstream" fix.

**Pull request merged**
