### PR TITLE
Use Nix to provision a now complete Docker container.

### PR DESCRIPTION
**Pull request by mboes**
The previous Docker container for the project included Java, but not
Spark. So while it was enough to *build* sparkle, it wasn't enough to
run Spark applications built using sparkle. This new Docker image
contains everything that is needed to both build and run apps.

In order to avoid the Nix shell.nix and the Docker Dockerfile from
drifting away from each other over time, we actually provision nearly
all system dependencies in the image using Nix. However, we *don't*
use Stack's --nix support nested inside Stack's --docker support.
Instead, we crafted a special entrypoint for the container that makes
Stack oblivious to the very existence of Nix. Stack just blithely
grabs stuff from the current PATH, however it was provided to it by
Nix.

### CODE REVIEW

**Comment by mboes** [comment]
Acceptance criteria:
* spark-submit works even when using `--docker` (see README).
* works on OS X.

**Comment by robinbb** [comment]
@mboes I have made documentation changes. Let me know what you think, please.

**Comment by facundominguez** [comment]
I just submitted a fix to the error I got when trying docker
```
$ stack --docker --docker-image sparkle build
Running /usr/sbin/useradd -oN --uid 1000 --gid 1000 --home /home/facundo/tweag/leapyear/sparkle/.stack-work/docker/_home stack exited with ExitFailure 6


useradd: group '1000' does not exist
useradd: the GROUP= configuration in /etc/default/useradd will be ignored
useradd: group '1000' does not exist
```
Spark builds both with nix and docker for me now.

**Comment by facundominguez** [comment]
@robinbb, if the fix works for you, it wouldn't be necessary to create a container and use `--allow-different-user` as the readme says.

**Comment by robinbb** [comment]
@facundominguez Your fix does not break my build. My build was working without your fix, mind you, but I was not building (from Mac) by following the instructions, exactly. In any case, I merged the fix under the assumption that those using Docker from a Linux host will need it. (Though, it was working for @mboes, clearly.)

**Comment by facundominguez** [comment]
Ok, I thought it could be issue (1) mentioned here:
https://leapyear.slack.com/archives/well-typed/p1479492414000727

**Comment by robinbb** [comment]
No, I think that issue was unrelated. That issue was due to sharing permissions of Docker, and maybe "stack --docker" issues, generally, on Mac.

**Pull request merged**
