### PR TITLE
Pin the nixpkgs version to a specific commit for reproducibility.

### PR DESCRIPTION
**Pull request by facundominguez**
Addresses #2.

### CODE REVIEW

**Comment by robinbb** [comment]
@facundominguez This will work for those who build via 'stack --nix', maybe. However, confusingly, the settings in stack.yaml are not consulted when sparkle is built with 'stack --docker --docker-image'. In that case, the shell.nix file determines the version of nixpkgs used, and that is done via the NIX_PATH environment variable of the builder. We should arrange for 'stack --nix' to use the given shell.nix with the right settings in stack.yaml (see https://docs.haskellstack.org/en/stable/nix_integration/#using-a-custom-shellnix-file) and then we should arrange for shell.nix to use the proper nixpkgs commit.

I propose that we consult @mboes to see what he had in mind for this matter, since we would like to upstream this change.

**Comment by mboes** [comment]
Ideally `stack --docker --nix` would work just fine. But unfortunately Stack isn't as composable as one might expect. If we fixed that, it would be a pain to use in any case until a new Stack release because all users would have to compile their Stack from current `master` before building sparkle. So instead I opted to add a hacked entrypoint to the Docker container. What this means in the meantime is that the only common control path between `stack --nix` and `stack --docker` is the shell.nix. So that's where we need to set the nixpkgs.

**Comment by facundominguez** [comment]
PTAL

**Comment by robinbb** [comment]
I am testing this, now. @facundominguez out of curiosity, how did you choose the commit? Also, how did you obtain that sha256?

**Comment by facundominguez** [comment]
For the sha I first try it with a dummy value, then nix tells me what's the sha it expects, and then I replace it with that.

For the commit, it was nixpkgs-unstable at the time I submitted this PR.

**Pull request merged**
