### PR TITLE
Update to GHC 8.0.2

### PR DESCRIPTION
**Pull request by robinbb**

### CODE REVIEW

**Comment by alpmestan** [comment]
CI killed the build for exceeding the time limit :disappointed:

**Comment by robinbb** [comment]
Yeah, bad. We'll have to increase the time limit. Meanwhile, does it build for you, @alpmestan ?

**Comment by alpmestan** [comment]
It does, but `default.nix`/`nix-build` ends up using 8.0.2 while `shell.nix`/`nix-shell`-then-`./build.sh` uses 8.0.1.

**Comment by robinbb** [comment]
I think that nix-shell is launched with a more recent version of Stack (see `stack --version`), but that the stack.yaml file is still specifying LTS-7.14, which uses GHC 8.0.1 for builds. So, all that this patch changes is the GHC version for the nix-build style of build, and the Stack version that performs the nix-shell style of build. Can we accept that for starters?

**Comment by alpmestan** [comment]
Yes, if we're fine with `buiild.sh` not using ghc 8.0.2. Accepting the PR, I'm leaving that call to you.

**Comment by shijinabraham-leapyear** [comment]
The dockerfile doesn't have the ./build.sh command. That was not run in the Concourse build.

**Comment by robinbb** [comment]
Moving to LeapYear/leapyear-sparkle repo.

**Pull request closed without merging**
